// ! DO NOT EDIT THIS FILE
import { Anchor, Log, Modify, Types, UI } from "jsonui-scripting";
import { CONFIGS } from "../.custom/config";
import path from "path";

export let bgContainer: UI<Types.Panel>;

switch (CONFIGS.support) {
    case "betmc_ui": {
        bgContainer = UI.panel({
            size: "100%",
            anchor: Anchor.Center
        }, {
            name: "betmc_animation_background_frame",
            namespace: "betmc_background"
        });

        Modify.register("betmc_config/config.json", "betmc_main_config").override.setProperties({
            $use_background_static_customs: false,
            $use_setting_background_static_customs: false,
            $use_background_animation: true
        });
    }
        break;

    default: {
        Log.error(`'${CONFIGS.support}' is not supported. Check ${path.join(__dirname, "../.custom/config.ts")}`);
        process.exitCode = 1;
    }
}
