name: Generator Animation Background

on:
    push:
        branches: main

permissions:
    contents: write

jobs:
    Generator:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Setup FFmpeg
              uses: AnimMouse/setup-ffmpeg@v1

            - name: Install dependencies
              run: bun install

            - name: Run
              run: bun run build

            - name: Upload UI build file
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  path: Minecraft-UIBuild.mcpack
